### ISSUE TITLE
add the possibility to have vertical tile in the expanded category

### ISSUE THREAD

**Issue by Rihan9** [xBourner/status-card#16]
Hi,
I'd like to have the entities in the pop-up in vertical mode instead horizontal.

From this:
![image](https://github.com/user-attachments/assets/1fdabe59-6b83-4f80-923a-d6afd49ec46f)

To something like this:
![image](https://github.com/user-attachments/assets/19666314-f948-4398-8599-2938b0f4e984)

Otherwise some sort of config to set the maximum column allowed. My goal is to concentrate the entities better on the center of the page in a more vertical-ish stilying.

Do you think it can be possible?

Thanks!

**Comment by xBourner** [comment]
yeah i think this would be possible. but im not sure at the moment if this is worth it. the pop up will show default tile cards which have this kinda look. i extended them so 4 tiles fit next together. if there are 100+ entities its a pain to scroll so i think the way it fits most people is this layout.

maybe there is an easy fix with grids and a config to change the grid columns but i am not focussing on that for now.
maybe i find some time for it. i will keep this open and see what i can do

**Comment by xBourner** [comment]
i was busy the last weeks with changed my .js project to .ts but i am almost done and added a number selector to change the columns in the more info view.
 for now its set to minimum 1 and max to 4
 
 
![image](https://github.com/user-attachments/assets/9c9ce3a4-ee72-4112-a93c-8557ca30b63b)


![image](https://github.com/user-attachments/assets/7500bfe4-8a38-43f0-9b47-e51e8fc47835)

![image](https://github.com/user-attachments/assets/12d79dce-92f0-4164-b4eb-822e67c455a0)

![image](https://github.com/user-attachments/assets/13af9850-e117-4591-8ca7-474527ee6279)
![image](https://github.com/user-attachments/assets/40c576db-9e09-4061-b329-a7f5190c2600)

![image](https://github.com/user-attachments/assets/a2ba509c-434a-48af-80a1-5c6421b803f8)
![image](https://github.com/user-attachments/assets/e58f4959-656c-4f2e-aea5-655dca5310a5)
![image](https://github.com/user-attachments/assets/ad6a53fa-9193-4e97-931d-a31e31cd6139)


it will take a while because i want to add one more feature before releasing it. i hope i can do this before christmas otherwise i think the next release would be in early januar

**Comment by xBourner** [comment]
shold be fixed in [v2.4.0]https://github.com/xBourner/status-card/releases/tag/v2.4.0
please check and give some feedback

**Comment by Rihan9** [comment]
Hi,
Sorry for the late replay. I tried the change and I love It! Thank you!
